/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.kafka
import io.micronaut.runtime.Micronaut.*

fun main(args: Array<String>) {
    build()
        .args(*args)
        .packages("hello.kafka")
        .start()
}
